// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0, demoIndex as dmi0 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormButtonGroup.zh-CN.md?type=frontmatter';
import { frontmatter as fm1, toc as t1, demoIndex as dmi1 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCollapse.zh-CN.md?type=frontmatter';
import { frontmatter as fm2, toc as t2, demoIndex as dmi2 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormCollapse.zh-CN.md?type=frontmatter';
import { frontmatter as fm3, toc as t3, demoIndex as dmi3 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/NumberPicker.zh-CN.md?type=frontmatter';
import { frontmatter as fm4, toc as t4, demoIndex as dmi4 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/SelectTable.zh-CN.md?type=frontmatter';
import { frontmatter as fm5, toc as t5, demoIndex as dmi5 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCards.zh-CN.md?type=frontmatter';
import { frontmatter as fm6, toc as t6, demoIndex as dmi6 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayItems.zh-CN.md?type=frontmatter';
import { frontmatter as fm7, toc as t7, demoIndex as dmi7 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTable.zh-CN.md?type=frontmatter';
import { frontmatter as fm8, toc as t8, demoIndex as dmi8 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/DatePicker.zh-CN.md?type=frontmatter';
import { frontmatter as fm9, toc as t9, demoIndex as dmi9 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDialog.zh-CN.md?type=frontmatter';
import { frontmatter as fm10, toc as t10, demoIndex as dmi10 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDrawer.zh-CN.md?type=frontmatter';
import { frontmatter as fm11, toc as t11, demoIndex as dmi11 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormLayout.zh-CN.md?type=frontmatter';
import { frontmatter as fm12, toc as t12, demoIndex as dmi12 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TimePicker.zh-CN.md?type=frontmatter';
import { frontmatter as fm13, toc as t13, demoIndex as dmi13 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TreeSelect.zh-CN.md?type=frontmatter';
import { frontmatter as fm14, toc as t14, demoIndex as dmi14 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTabs.zh-CN.md?type=frontmatter';
import { frontmatter as fm15, toc as t15, demoIndex as dmi15 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormButtonGroup.md?type=frontmatter';
import { frontmatter as fm16, toc as t16, demoIndex as dmi16 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Cascader.zh-CN.md?type=frontmatter';
import { frontmatter as fm17, toc as t17, demoIndex as dmi17 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Checkbox.zh-CN.md?type=frontmatter';
import { frontmatter as fm18, toc as t18, demoIndex as dmi18 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Editable.zh-CN.md?type=frontmatter';
import { frontmatter as fm19, toc as t19, demoIndex as dmi19 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormGrid.zh-CN.md?type=frontmatter';
import { frontmatter as fm20, toc as t20, demoIndex as dmi20 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormItem.zh-CN.md?type=frontmatter';
import { frontmatter as fm21, toc as t21, demoIndex as dmi21 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormStep.zh-CN.md?type=frontmatter';
import { frontmatter as fm22, toc as t22, demoIndex as dmi22 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Password.zh-CN.md?type=frontmatter';
import { frontmatter as fm23, toc as t23, demoIndex as dmi23 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Transfer.zh-CN.md?type=frontmatter';
import { frontmatter as fm24, toc as t24, demoIndex as dmi24 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCollapse.md?type=frontmatter';
import { frontmatter as fm25, toc as t25, demoIndex as dmi25 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormTab.zh-CN.md?type=frontmatter';
import { frontmatter as fm26, toc as t26, demoIndex as dmi26 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormCollapse.md?type=frontmatter';
import { frontmatter as fm27, toc as t27, demoIndex as dmi27 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/NumberPicker.md?type=frontmatter';
import { frontmatter as fm28, toc as t28, demoIndex as dmi28 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Select.zh-CN.md?type=frontmatter';
import { frontmatter as fm29, toc as t29, demoIndex as dmi29 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Submit.zh-CN.md?type=frontmatter';
import { frontmatter as fm30, toc as t30, demoIndex as dmi30 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Switch.zh-CN.md?type=frontmatter';
import { frontmatter as fm31, toc as t31, demoIndex as dmi31 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Upload.zh-CN.md?type=frontmatter';
import { frontmatter as fm32, toc as t32, demoIndex as dmi32 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/index.zh-CN.md?type=frontmatter';
import { frontmatter as fm33, toc as t33, demoIndex as dmi33 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Input.zh-CN.md?type=frontmatter';
import { frontmatter as fm34, toc as t34, demoIndex as dmi34 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Radio.zh-CN.md?type=frontmatter';
import { frontmatter as fm35, toc as t35, demoIndex as dmi35 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Reset.zh-CN.md?type=frontmatter';
import { frontmatter as fm36, toc as t36, demoIndex as dmi36 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/SelectTable.md?type=frontmatter';
import { frontmatter as fm37, toc as t37, demoIndex as dmi37 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Space.zh-CN.md?type=frontmatter';
import { frontmatter as fm38, toc as t38, demoIndex as dmi38 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCards.md?type=frontmatter';
import { frontmatter as fm39, toc as t39, demoIndex as dmi39 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayItems.md?type=frontmatter';
import { frontmatter as fm40, toc as t40, demoIndex as dmi40 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTable.md?type=frontmatter';
import { frontmatter as fm41, toc as t41, demoIndex as dmi41 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/DatePicker.md?type=frontmatter';
import { frontmatter as fm42, toc as t42, demoIndex as dmi42 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Form.zh-CN.md?type=frontmatter';
import { frontmatter as fm43, toc as t43, demoIndex as dmi43 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDialog.md?type=frontmatter';
import { frontmatter as fm44, toc as t44, demoIndex as dmi44 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDrawer.md?type=frontmatter';
import { frontmatter as fm45, toc as t45, demoIndex as dmi45 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormLayout.md?type=frontmatter';
import { frontmatter as fm46, toc as t46, demoIndex as dmi46 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TimePicker.md?type=frontmatter';
import { frontmatter as fm47, toc as t47, demoIndex as dmi47 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TreeSelect.md?type=frontmatter';
import { frontmatter as fm48, toc as t48, demoIndex as dmi48 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTabs.md?type=frontmatter';
import { frontmatter as fm49, toc as t49, demoIndex as dmi49 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Cascader.md?type=frontmatter';
import { frontmatter as fm50, toc as t50, demoIndex as dmi50 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Checkbox.md?type=frontmatter';
import { frontmatter as fm51, toc as t51, demoIndex as dmi51 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Editable.md?type=frontmatter';
import { frontmatter as fm52, toc as t52, demoIndex as dmi52 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormGrid.md?type=frontmatter';
import { frontmatter as fm53, toc as t53, demoIndex as dmi53 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormItem.md?type=frontmatter';
import { frontmatter as fm54, toc as t54, demoIndex as dmi54 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormStep.md?type=frontmatter';
import { frontmatter as fm55, toc as t55, demoIndex as dmi55 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Password.md?type=frontmatter';
import { frontmatter as fm56, toc as t56, demoIndex as dmi56 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Transfer.md?type=frontmatter';
import { frontmatter as fm57, toc as t57, demoIndex as dmi57 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormTab.md?type=frontmatter';
import { frontmatter as fm58, toc as t58, demoIndex as dmi58 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Select.md?type=frontmatter';
import { frontmatter as fm59, toc as t59, demoIndex as dmi59 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Submit.md?type=frontmatter';
import { frontmatter as fm60, toc as t60, demoIndex as dmi60 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Switch.md?type=frontmatter';
import { frontmatter as fm61, toc as t61, demoIndex as dmi61 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Upload.md?type=frontmatter';
import { frontmatter as fm62, toc as t62, demoIndex as dmi62 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/index.md?type=frontmatter';
import { frontmatter as fm63, toc as t63, demoIndex as dmi63 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Input.md?type=frontmatter';
import { frontmatter as fm64, toc as t64, demoIndex as dmi64 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Radio.md?type=frontmatter';
import { frontmatter as fm65, toc as t65, demoIndex as dmi65 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Reset.md?type=frontmatter';
import { frontmatter as fm66, toc as t66, demoIndex as dmi66 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Space.md?type=frontmatter';
import { frontmatter as fm67, toc as t67, demoIndex as dmi67 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Form.md?type=frontmatter';
import { frontmatter as fm68, toc as t68, demoIndex as dmi68 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/index.zh-CN.md?type=frontmatter';
import { frontmatter as fm69, toc as t69, demoIndex as dmi69 } from 'D:/develop/workspace/triones/npms/formilyjs-antd/docs/index.md?type=frontmatter';

export const filesMeta = {
  'docs/components/FormButtonGroup.zh-CN': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormButtonGroup.zh-CN.md?type=text'),
  },
  'docs/components/ArrayCollapse.zh-CN': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCollapse.zh-CN.md?type=text'),
  },
  'docs/components/FormCollapse.zh-CN': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormCollapse.zh-CN.md?type=text'),
  },
  'docs/components/NumberPicker.zh-CN': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/NumberPicker.zh-CN.md?type=text'),
  },
  'docs/components/SelectTable.zh-CN': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/SelectTable.zh-CN.md?type=text'),
  },
  'docs/components/ArrayCards.zh-CN': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCards.zh-CN.md?type=text'),
  },
  'docs/components/ArrayItems.zh-CN': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayItems.zh-CN.md?type=text'),
  },
  'docs/components/ArrayTable.zh-CN': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTable.zh-CN.md?type=text'),
  },
  'docs/components/DatePicker.zh-CN': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/DatePicker.zh-CN.md?type=text'),
  },
  'docs/components/FormDialog.zh-CN': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDialog.zh-CN.md?type=text'),
  },
  'docs/components/FormDrawer.zh-CN': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDrawer.zh-CN.md?type=text'),
  },
  'docs/components/FormLayout.zh-CN': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormLayout.zh-CN.md?type=text'),
  },
  'docs/components/TimePicker.zh-CN': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TimePicker.zh-CN.md?type=text'),
  },
  'docs/components/TreeSelect.zh-CN': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TreeSelect.zh-CN.md?type=text'),
  },
  'docs/components/ArrayTabs.zh-CN': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTabs.zh-CN.md?type=text'),
  },
  'docs/components/FormButtonGroup': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormButtonGroup.md?type=text'),
  },
  'docs/components/Cascader.zh-CN': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Cascader.zh-CN.md?type=text'),
  },
  'docs/components/Checkbox.zh-CN': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Checkbox.zh-CN.md?type=text'),
  },
  'docs/components/Editable.zh-CN': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Editable.zh-CN.md?type=text'),
  },
  'docs/components/FormGrid.zh-CN': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormGrid.zh-CN.md?type=text'),
  },
  'docs/components/FormItem.zh-CN': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormItem.zh-CN.md?type=text'),
  },
  'docs/components/FormStep.zh-CN': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormStep.zh-CN.md?type=text'),
  },
  'docs/components/Password.zh-CN': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Password.zh-CN.md?type=text'),
  },
  'docs/components/Transfer.zh-CN': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Transfer.zh-CN.md?type=text'),
  },
  'docs/components/ArrayCollapse': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCollapse.md?type=text'),
  },
  'docs/components/FormTab.zh-CN': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormTab.zh-CN.md?type=text'),
  },
  'docs/components/FormCollapse': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormCollapse.md?type=text'),
  },
  'docs/components/NumberPicker': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/NumberPicker.md?type=text'),
  },
  'docs/components/Select.zh-CN': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Select.zh-CN.md?type=text'),
  },
  'docs/components/Submit.zh-CN': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Submit.zh-CN.md?type=text'),
  },
  'docs/components/Switch.zh-CN': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Switch.zh-CN.md?type=text'),
  },
  'docs/components/Upload.zh-CN': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Upload.zh-CN.md?type=text'),
  },
  'docs/components/index.zh-CN': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/index.zh-CN.md?type=text'),
  },
  'docs/components/Input.zh-CN': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Input.zh-CN.md?type=text'),
  },
  'docs/components/Radio.zh-CN': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Radio.zh-CN.md?type=text'),
  },
  'docs/components/Reset.zh-CN': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Reset.zh-CN.md?type=text'),
  },
  'docs/components/SelectTable': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/SelectTable.md?type=text'),
  },
  'docs/components/Space.zh-CN': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Space.zh-CN.md?type=text'),
  },
  'docs/components/ArrayCards': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayCards.md?type=text'),
  },
  'docs/components/ArrayItems': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayItems.md?type=text'),
  },
  'docs/components/ArrayTable': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTable.md?type=text'),
  },
  'docs/components/DatePicker': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/DatePicker.md?type=text'),
  },
  'docs/components/Form.zh-CN': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Form.zh-CN.md?type=text'),
  },
  'docs/components/FormDialog': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDialog.md?type=text'),
  },
  'docs/components/FormDrawer': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormDrawer.md?type=text'),
  },
  'docs/components/FormLayout': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormLayout.md?type=text'),
  },
  'docs/components/TimePicker': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TimePicker.md?type=text'),
  },
  'docs/components/TreeSelect': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/TreeSelect.md?type=text'),
  },
  'docs/components/ArrayTabs': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/ArrayTabs.md?type=text'),
  },
  'docs/components/Cascader': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Cascader.md?type=text'),
  },
  'docs/components/Checkbox': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Checkbox.md?type=text'),
  },
  'docs/components/Editable': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Editable.md?type=text'),
  },
  'docs/components/FormGrid': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormGrid.md?type=text'),
  },
  'docs/components/FormItem': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormItem.md?type=text'),
  },
  'docs/components/FormStep': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormStep.md?type=text'),
  },
  'docs/components/Password': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Password.md?type=text'),
  },
  'docs/components/Transfer': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Transfer.md?type=text'),
  },
  'docs/components/FormTab': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/FormTab.md?type=text'),
  },
  'docs/components/Select': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Select.md?type=text'),
  },
  'docs/components/Submit': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Submit.md?type=text'),
  },
  'docs/components/Switch': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Switch.md?type=text'),
  },
  'docs/components/Upload': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Upload.md?type=text'),
  },
  'docs/components/index': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/index.md?type=text'),
  },
  'docs/components/Input': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Input.md?type=text'),
  },
  'docs/components/Radio': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Radio.md?type=text'),
  },
  'docs/components/Reset': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Reset.md?type=text'),
  },
  'docs/components/Space': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Space.md?type=text'),
  },
  'docs/components/Form': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/components/Form.md?type=text'),
  },
  'docs/index.zh-CN': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/index.zh-CN.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/develop/workspace/triones/npms/formilyjs-antd/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
