// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/develop/workspace/triones/npms/formilyjs-antd/node_modules/.pnpm/dumi@2.4.45_@babel+core@7.2_21a0200d2e2844a126ce035381d0820b/node_modules/dumi/theme-default/slots/Tabs/index.js';
