// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/develop/workspace/triones/npms/formilyjs-antd/node_modules/.pnpm/@umijs+renderer-react@4.6.7_aedb8ee77d77bfeaffc47138ee59bdb5/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
