// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from 'D:/develop/workspace/triones/npms/formilyjs-antd/node_modules/.pnpm/rc-util@5.44.4_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/rc-util';
import { SiteContext, type ISiteContext } from 'D:/develop/workspace/triones/npms/formilyjs-antd/node_modules/.pnpm/dumi@2.4.45_@babel+core@7.2_21a0200d2e2844a126ce035381d0820b/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"root","repository":{"type":"git","url":"git+https://github.com/formilyjs/antd.git"}};
const historyType = "browser";
const hostname = "";
const themeConfig = {"footer":"Open-source MIT Licensed | Copyright © 2019-present<br />Powered by self","prefersColor":{"default":"light","switch":false},"nprogress":true,"lastUpdated":true,"name":"Formily Antd","logo":"//img.alicdn.com/imgextra/i2/O1CN01Kq3OHU1fph6LGqjIz_!!6000000004056-55-tps-1141-150.svg","nav":{"en-US":[{"title":"Ant Design 6","link":"/components"},{"title":"Home Site","link":"https://formilyjs.org"},{"title":"GITHUB","link":"https://github.com/formilyjs/antd"}],"zh-CN":[{"title":"Ant Design 6","link":"/zh-CN/components"},{"title":"主站","link":"https://v2.formilyjs.org/"},{"title":"GITHUB","link":"https://github.com/formilyjs/antd"}]},"sourceLink":"https://github.com/formilyjs/antd/tree/bane%2Fantd6-upgrade/{fileName}#L{line}","editLink":"https://github.com/formilyjs/antd/edit/bane%2Fantd6-upgrade/{filename}"};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
